sudo: required
language: python

python:
  - "3.8"

install:
  - "$TRAVIS_BUILD_DIR/scripts/setup.sh"
  - "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"

script:
  - echo "skipping tests"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/deploy.sh --deploy
    on:
      branch: main
